version: '3'

services: 
  db:
    container_name: quotedb
    image: postgres
    hostname: db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - 5432:5432
    networks:
      - quotenet
  
  quoteapi:
    container_name: quoteapi
    image: rahmancam/quoteapi:v1
    hostname: quoteapi
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      DB_HOST: db 
      DB_USER: postgres-dev
      DB_PASSWORD: mysecretpassword
      DB_NAME: dev
    networks: 
      - quotenet
    volumes: 
      - .:/go/src/github.com/rahmancam/qo-quote-api
    ports:
      - 8080:8080
    depends_on: 
      - db
    links: 
      - db

networks:
  quotenet:
    driver: bridge 
      


